### ISSUE TITLE
切换 library 以后，任务还在执行

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/tauri-dam-test-playground#2]

**Comment by web3nomad** [comment]
任务的中断，应该可以用这个逻辑来实现，我试试加在init_task_pool那里
https://tokio.rs/tokio/topics/shutdown

**Comment by zhuojg** [comment]
this minimal demo works:

```rust
use std::sync::Arc;
use tokio::sync::broadcast::{self, Sender};
use tokio_util::sync::CancellationToken;

#[test_log::test(tokio::test)]
async fn test_cancel_tasks() {
    let token = CancellationToken::new();

    let (tx, _rx) = broadcast::channel::<u64>(500);

    let tx = Arc::new(tx);
    let mut rx = tx.subscribe();

    let cloned_token = token.clone();

    tokio::spawn(async move {
        loop {
            match rx.recv().await {
                Ok(t) => {
                    tokio::select! {
                        _ = cloned_token.cancelled() => {
                            tracing::info!("Task shutdown")
                        }
                        _ = tokio::time::sleep(std::time::Duration::from_secs(t)) => {
                            // Long work has completed
                            tracing::info!("Task finished {}", t);
                        }
                    }
                }
                Err(e) => {
                    tracing::error!("No Task Error: {:?}", e);
                }
            }
        }
    });

    tx.send(3).unwrap();
    tx.send(3).unwrap();
    tx.send(3).unwrap();
    tx.send(3).unwrap();

    tokio::time::sleep(std::time::Duration::from_secs(5)).await;
    token.cancel();
    tokio::time::sleep(std::time::Duration::from_secs(10)).await;
}

```

The output:
```
2024-03-20T11:03:49.079394Z  INFO api_server::task_queue::pool: Task finished 3
2024-03-20T11:03:51.078990Z  INFO api_server::task_queue::pool: Task shutdown
2024-03-20T11:03:51.079063Z  INFO api_server::task_queue::pool: Task shutdown
2024-03-20T11:03:51.079074Z  INFO api_server::task_queue::pool: Task shutdown
```

**Comment by zhuojg** [comment]
> > 任务的中断，应该可以用这个逻辑来实现，https://tokio.rs/tokio/topics/shutdown
> 
> this minimal demo works:
> 
> ```rust
> use std::sync::Arc;
> use tokio::sync::broadcast::{self, Sender};
> use tokio_util::sync::CancellationToken;
> 
> #[test_log::test(tokio::test)]
> async fn test_cancel_tasks() {
>     let token = CancellationToken::new();
> 
>     let (tx, _rx) = broadcast::channel::<u64>(500);
> 
>     let tx = Arc::new(tx);
>     let mut rx = tx.subscribe();
> 
>     let cloned_token = token.clone();
> 
>     tokio::spawn(async move {
>         loop {
>             match rx.recv().await {
>                 Ok(t) => {
>                     tokio::select! {
>                         _ = cloned_token.cancelled() => {
>                             tracing::info!("Task shutdown")
>                         }
>                         _ = tokio::time::sleep(std::time::Duration::from_secs(t)) => {
>                             // Long work has completed
>                             tracing::info!("Task finished {}", t);
>                         }
>                     }
>                 }
>                 Err(e) => {
>                     tracing::error!("No Task Error: {:?}", e);
>                 }
>             }
>         }
>     });
> 
>     tx.send(3).unwrap();
>     tx.send(3).unwrap();
>     tx.send(3).unwrap();
>     tx.send(3).unwrap();
> 
>     tokio::time::sleep(std::time::Duration::from_secs(5)).await;
>     token.cancel();
>     tokio::time::sleep(std::time::Duration::from_secs(10)).await;
> }
> ```
> 
> The output:
> 
> ```
> 2024-03-20T11:03:49.079394Z  INFO api_server::task_queue::pool: Task finished 3
> 2024-03-20T11:03:51.078990Z  INFO api_server::task_queue::pool: Task shutdown
> 2024-03-20T11:03:51.079063Z  INFO api_server::task_queue::pool: Task shutdown
> 2024-03-20T11:03:51.079074Z  INFO api_server::task_queue::pool: Task shutdown
> ```

Implement task cancelation in deb107221cd17669a7c12b51a697c3cae3d5a54f.

---

有两个问题：
1. 创建task后cpu占用变高，取消任务（切换library）后没有回到原来的水平
    - desktop 应用启动后cpu占用大概就5%以内，取消任务后确实没执行了，但cpu占用还是很高，大概100%左右
    - 另一个发现：任务正常执行完，cpu占用也是100%左右，不会下降到一开始的水平
    - 所以可能还是任务执行本身的bug
2. Ctx的方法好像不能用&mut self，所以没法修改某个字段，我暂时像别的字段一样写成了Arc<Mutex<xxx>>（在切换library的时候要像更新library一样更新tx和cancel_token），不知道这里有没有更好的写法

![img_v3_0295_f2e7cd8d-fb33-4490-b294-90abfb5374eg](https://github.com/bmrlab/tauri-dam-test-playground/assets/24386525/ce63bf71-440b-4bc2-a92b-2e4a4c842f84)

**Comment by zhuojg** [comment]
cpu 占用的问题，可能可以通过 #5 来解决

**Comment by zhuojg** [comment]
> cpu 占用的问题，可能可以通过 #5 来解决

这个问题在 e75b3817b5c6cfe7ca535fe1b563332d9811687f 已经观察不到了，可能是因为：
- rspc 切换到 0.2.0
- 解决了 #5 

先 close issue 了
