### ISSUE TITLE
优化 hash，library 采用 uuid，文件采用更短的 hash，在本地 shard 存储

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/tauri-dam-test-playground#35]
spacedrive 生成 hash 的算法，看起来更快

https://github.com/spacedriveapp/spacedrive/blob/204c876689dc113713e63acf441a4a1281227a2d/core/src/object/cas.rs#L23

spacedrive 生成 shard 的方法，取 hash 的 0..3，作为子文件夹

https://github.com/spacedriveapp/spacedrive/blob/204c876689dc113713e63acf441a4a1281227a2d/core/src/object/media/old_thumbnail/shard.rs#L10

- [x] 改用 [blake3](https://docs.rs/blake3/latest/blake3/) 进行采样哈希
- [x] artifacts 和 files 目录使用 sharding

**Comment by zhuojg** [comment]
spacedrive 现在应该只有 `thumbnails` 用到了 `sharding`

<img width="732" alt="image" src="https://github.com/bmrlab/tauri-dam-test-playground/assets/24386525/37aac1d7-b013-4440-8c75-537bfed3ff58">


我先不改变目录结构，在 `files` 和 `artifacts` 文件夹里都加一下 `sharding`

当前：
```shell
├── artifacts
│   ├── 5adec370b6040f26
│   │   ├── audio.wav
│   │   ├── frames
│   │   │   ├── ...
│   │   ├── thumbnail.jpg
│   │   └── transcript.txt
├── files
│   ├── 5adec370b6040f26
│   └── ...
...
```

增加 `sharding` 后
```shell
├── artifacts
│   ├── 5ad
│   │   ├── 5adec370b6040f26
│   │   │   ├── audio.wav
│   │   │   ├── frames
│   │   │   │   ├── ...
│   │   │   ├── thumbnail.jpg
│   │   │   └── transcript.txt
├── files
│   ├── 5ad
│   │   ├── 5adec370b6040f26
│   │   └── ...
```

**Comment by zhuojg** [comment]
当前目录结构

<img width="1272" alt="image" src="https://github.com/bmrlab/tauri-dam-test-playground/assets/24386525/a4befa3a-e2ab-4e97-9ef8-215f6883f27d">

<img width="944" alt="image" src="https://github.com/bmrlab/tauri-dam-test-playground/assets/24386525/30c2171e-d978-4680-a52c-3525222ca17d">
