### ISSUE TITLE
向量数据库的 payload 过滤代码还有待优化，包括枚举值的自动生成以及payload的格式

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/tauri-dam-test-playground#4]
现在直接用SearchPayload转为json，多了一层没有用的数据

**Comment by zhuojg** [comment]
用 `serde` 可以很简单地解决这个问题，已经在 72cdeec880e6aea2625210986c651b1d97581cb6 中加入了这个优化

https://serde.rs/enum-representations.html#internally-tagged

<img width="624" alt="image" src="https://github.com/bmrlab/tauri-dam-test-playground/assets/24386525/d827791e-a14b-4037-8d41-f8bcfb00a7eb">

**Comment by zhuojg** [comment]
枚举值自动生成则可以通过 `strum` 的 `EnumDiscriminants` 特性实现

https://docs.rs/strum_macros/latest/strum_macros/derive.EnumDiscriminants.html
