### ISSUE TITLE
提交了视频任务以后，rspc 接口会卡住一会儿

### ISSUE THREAD

**Issue by web3nomad** [bmrlab/tauri-dam-test-playground#6]
有可能是某个资源被锁住，也有可能是拿不到 prisma client pool 里面的 connection，因为现在限制了 connection_limit=1

- [x] 需要给 video 的任务都加上重试机制。
- [ ] 文件上传失败重试

**Comment by web3nomad** [comment]
现在的设置是 socket_timeout=15&connection_limit=1
批量上传的时候会偶尔有一个失败，原因就是启动 db transaction 超时。也是加上重试功能就行了。

- [ ] 文件上传失败重试

**Comment by zhuojg** [comment]
感觉是在生成 video caption 的时候卡得比较明显，尝试进行一下资源占用的限制，保证主进程不卡
